#stage1
FROM node:16-alpine as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

#staage 2
FROM nginx:alpine
#COPY --from=node /app /app
COPY --from=node /app/dist/calculadora-hidratacao-na-dengue/browser /usr/share/nginx/html
